import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { EdgeStoreProvider } from '@/app/lib/edgestore';
import './globals.css';
import NavBar from './ui/home/nav-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex-none p-4">
          <NavBar />
        </div>
        <EdgeStoreProvider>{children}</EdgeStoreProvider>
      </body>
    </html>
  );
}
